export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const User_Profile_Data = "User_Profile_Data"
export const USER_MESSAGE = "USER_MESSAGE"
export const SELECTED_LIBRARY = "SELECTED_LIBRARY"
export const USER_SELECTED_ID = "USER_SELECTED_ID"